services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: github-repos-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-your-secret-encryption-key-change-this-in-production}
      - DATABASE_PATH=/app/data/app.db
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3001/api
    container_name: github-repos-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
